# Generated by Django 5.0.4 on 2024-05-10 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clan_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.IntegerField()),
                ('match_date', models.DateTimeField()),
                ('message', models.TextField()),
                ('is_accepted', models.BooleanField(verbose_name='')),
                ('invitee_clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to='clan_pages.clan', verbose_name='')),
                ('inviter_clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to='clan_pages.clan', verbose_name='')),
            ],
        ),
    ]
