# Generated by Django 5.0.4 on 2024-05-14 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_pages', '0002_alter_clan_user_alter_clan_clan_name_and_more'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_type',
            field=models.CharField(choices=[('', 'Select from the list below'), ('18vs18', '18vs18'), ('50vs50', '50vs50'), ('30vs30', '30vs30'), ('Tank', 'Tank'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='invitee_clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to='clan_pages.clan', verbose_name='Invitee'),
        ),
        migrations.AlterField(
            model_name='match',
            name='inviter_clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to='clan_pages.clan', verbose_name='Inviter'),
        ),
        migrations.AlterField(
            model_name='match',
            name='is_accepted',
            field=models.BooleanField(verbose_name='Is Accepted'),
        ),
    ]
