# Generated by Django 5.0.4 on 2024-05-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_game_type_alter_match_invitee_clan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='is_accepted',
            field=models.CharField(choices=[('accepted', 'accepted'), ('in-progress', 'in-progress'), ('rejected', 'rejected')], default='in-progress', max_length=50),
        ),
    ]
