# Generated by Django 5.0.4 on 2024-05-10 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_representative', models.BooleanField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_name', models.CharField(max_length=50, verbose_name='')),
                ('content', models.CharField(max_length=50, verbose_name='')),
                ('image_url', models.CharField(max_length=50, verbose_name='')),
                ('discord_url', models.CharField(max_length=50, verbose_name='')),
                ('website_url', models.CharField(max_length=50, verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clan_pages.user', verbose_name='')),
            ],
        ),
    ]
