# Generated by Django 5.0.4 on 2024-05-14 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='clan_name',
            field=models.CharField(max_length=50, verbose_name='Clan Name'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='content',
            field=models.CharField(max_length=50, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='discord_url',
            field=models.CharField(max_length=50, verbose_name='Discord URL'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='image_url',
            field=models.CharField(max_length=50, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='website_url',
            field=models.CharField(max_length=50, verbose_name='Website URL'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
