# Generated by Django 5.0.4 on 2024-05-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_pages', '0002_alter_clan_user_alter_clan_clan_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='image_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='website_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Website URL'),
        ),
    ]
