# Generated by Django 5.0.4 on 2024-05-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_pages', '0003_alter_clan_image_url_alter_clan_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='content',
            field=models.CharField(max_length=2000, verbose_name='Content'),
        ),
    ]
