# Generated by Django 5.0.4 on 2024-05-10 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clan_pages', '0001_initial'),
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='')),
                ('status', models.IntegerField(verbose_name='')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clan_pages.clan', verbose_name='')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuer', to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match', verbose_name='')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
    ]
