# Generated by Django 5.0.4 on 2024-05-14 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_pages', '0002_alter_clan_user_alter_clan_clan_name_and_more'),
        ('matches', '0002_alter_match_game_type_alter_match_invitee_clan_and_more'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clan_pages.clan', verbose_name='Clan'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(max_length=50, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuer', to=settings.AUTH_USER_MODEL, verbose_name='Issuer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match', verbose_name='Match'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('in-progress', 'in-progress'), ('rejected', 'rejected')], max_length=50),
        ),
    ]
