# Generated by Django 5.0.4 on 2024-05-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_clan_alter_notification_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='match',
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(max_length=100, verbose_name='Content'),
        ),
    ]
